export const CHECKOUT_PAYMENT_METHOD = {
  QRIS: 'qris',
  GOPAY: 'gopay',
  GOPAY_DYNAMIC_QRIS: 'gopay_dynamic_qris',
  SEABANK: 'seabank',
  CIMB: 'cimb',
  BNI: 'bni',
  BRI: 'bri',
  MANDIRI: 'mandiri',
  PERMATA: 'permata',
  CARD: 'card',
} as const

export type CheckoutPaymentMethod =
  (typeof CHECKOUT_PAYMENT_METHOD)[keyof typeof CHECKOUT_PAYMENT_METHOD]

type PaymentFeeRule = {
  fixedAmount: number
  percentBps: number
}

export type PaymentMethodCatalogEntry = {
  id: CheckoutPaymentMethod
  title: string
  subtitle: string
  tone: string
  gatewayFeeRule: PaymentFeeRule
}

const LEGACY_PAYMENT_METHOD_CATALOG: Array<PaymentMethodCatalogEntry> = [
  {
    id: CHECKOUT_PAYMENT_METHOD.QRIS,
    title: 'QRIS',
    subtitle: 'Scan from any QRIS-enabled banking or wallet app',
    tone: 'Universal QR payment',
    gatewayFeeRule: { fixedAmount: 0, percentBps: 70 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.GOPAY,
    title: 'GoPay',
    subtitle: 'Pay with GoPay app or GoJek deeplink',
    tone: 'Wallet checkout',
    gatewayFeeRule: { fixedAmount: 0, percentBps: 200 },
  },
]

export const PAYMENT_METHOD_CATALOG: Array<PaymentMethodCatalogEntry> = [
  {
    id: CHECKOUT_PAYMENT_METHOD.GOPAY_DYNAMIC_QRIS,
    title: 'GoPay Dynamic QRIS',
    subtitle: 'Dynamic QRIS generated by GoPay',
    tone: 'Dynamic QR checkout',
    gatewayFeeRule: { fixedAmount: 0, percentBps: 70 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.SEABANK,
    title: 'SeaBank',
    subtitle: 'Transfer from SeaBank to a virtual account',
    tone: 'Bank app transfer',
    gatewayFeeRule: { fixedAmount: 4000, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.CIMB,
    title: 'CIMB Niaga',
    subtitle: 'CIMB virtual account transfer',
    tone: 'Virtual account',
    gatewayFeeRule: { fixedAmount: 4000, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.BNI,
    title: 'BNI',
    subtitle: 'BNI virtual account transfer',
    tone: 'Virtual account',
    gatewayFeeRule: { fixedAmount: 4000, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.BRI,
    title: 'BRI',
    subtitle: 'BRI virtual account transfer',
    tone: 'Virtual account',
    gatewayFeeRule: { fixedAmount: 4000, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.MANDIRI,
    title: 'Bank Mandiri',
    subtitle: 'Mandiri Bill Payment',
    tone: 'Bill payment',
    gatewayFeeRule: { fixedAmount: 4500, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.PERMATA,
    title: 'PermataBank',
    subtitle: 'Permata virtual account transfer',
    tone: 'Virtual account',
    gatewayFeeRule: { fixedAmount: 4000, percentBps: 0 },
  },
  {
    id: CHECKOUT_PAYMENT_METHOD.CARD,
    title: 'Credit / Debit Card',
    subtitle: '3DS-secured card payment',
    tone: 'Card checkout',
    gatewayFeeRule: { fixedAmount: 2000, percentBps: 290 },
  },
]

export const PLATFORM_SERVICE_FEE_BPS = 500

export function getPaymentMethodCatalogEntry(method: CheckoutPaymentMethod) {
  const found = [...PAYMENT_METHOD_CATALOG, ...LEGACY_PAYMENT_METHOD_CATALOG].find(
    (entry) => entry.id === method,
  )
  if (!found) {
    throw new Error(`Unsupported payment method: ${method}`)
  }
  return found
}

export function calculatePaymentGatewayFee(
  subtotalAmount: number,
  method: CheckoutPaymentMethod,
): number {
  const rule = getPaymentMethodCatalogEntry(method).gatewayFeeRule
  return rule.fixedAmount + Math.round((subtotalAmount * rule.percentBps) / 10000)
}

export function calculatePlatformServiceFee(subtotalAmount: number): number {
  return Math.round((subtotalAmount * PLATFORM_SERVICE_FEE_BPS) / 10000)
}
