/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestDndRouteImport } from './routes/test-dnd'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as UsernameAdminRouteRouteImport } from './routes/$username/admin/route'
import { Route as UsernameAdminIndexRouteImport } from './routes/$username/admin/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UsernameAdminAppearanceRouteImport } from './routes/$username/admin/appearance'

const TestDndRoute = TestDndRouteImport.update({
  id: '/test-dnd',
  path: '/test-dnd',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameAdminRouteRoute = UsernameAdminRouteRouteImport.update({
  id: '/$username/admin',
  path: '/$username/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameAdminIndexRoute = UsernameAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsernameAdminRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameAdminAppearanceRoute = UsernameAdminAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => UsernameAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/test-dnd': typeof TestDndRoute
  '/$username/admin': typeof UsernameAdminRouteRouteWithChildren
  '/$username/': typeof UsernameIndexRoute
  '/$username/admin/appearance': typeof UsernameAdminAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$username/admin/': typeof UsernameAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/test-dnd': typeof TestDndRoute
  '/$username': typeof UsernameIndexRoute
  '/$username/admin/appearance': typeof UsernameAdminAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$username/admin': typeof UsernameAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/test-dnd': typeof TestDndRoute
  '/$username/admin': typeof UsernameAdminRouteRouteWithChildren
  '/$username/': typeof UsernameIndexRoute
  '/$username/admin/appearance': typeof UsernameAdminAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$username/admin/': typeof UsernameAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/test-dnd'
    | '/$username/admin'
    | '/$username/'
    | '/$username/admin/appearance'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$username/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/test-dnd'
    | '/$username'
    | '/$username/admin/appearance'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$username/admin'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/test-dnd'
    | '/$username/admin'
    | '/$username/'
    | '/$username/admin/appearance'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$username/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  TestDndRoute: typeof TestDndRoute
  UsernameAdminRouteRoute: typeof UsernameAdminRouteRouteWithChildren
  UsernameIndexRoute: typeof UsernameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-dnd': {
      id: '/test-dnd'
      path: '/test-dnd'
      fullPath: '/test-dnd'
      preLoaderRoute: typeof TestDndRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/admin': {
      id: '/$username/admin'
      path: '/$username/admin'
      fullPath: '/$username/admin'
      preLoaderRoute: typeof UsernameAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/admin/': {
      id: '/$username/admin/'
      path: '/'
      fullPath: '/$username/admin/'
      preLoaderRoute: typeof UsernameAdminIndexRouteImport
      parentRoute: typeof UsernameAdminRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/admin/appearance': {
      id: '/$username/admin/appearance'
      path: '/appearance'
      fullPath: '/$username/admin/appearance'
      preLoaderRoute: typeof UsernameAdminAppearanceRouteImport
      parentRoute: typeof UsernameAdminRouteRoute
    }
  }
}

interface UsernameAdminRouteRouteChildren {
  UsernameAdminAppearanceRoute: typeof UsernameAdminAppearanceRoute
  UsernameAdminIndexRoute: typeof UsernameAdminIndexRoute
}

const UsernameAdminRouteRouteChildren: UsernameAdminRouteRouteChildren = {
  UsernameAdminAppearanceRoute: UsernameAdminAppearanceRoute,
  UsernameAdminIndexRoute: UsernameAdminIndexRoute,
}

const UsernameAdminRouteRouteWithChildren =
  UsernameAdminRouteRoute._addFileChildren(UsernameAdminRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  TestDndRoute: TestDndRoute,
  UsernameAdminRouteRoute: UsernameAdminRouteRouteWithChildren,
  UsernameIndexRoute: UsernameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
