/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UsernameIndexRouteImport } from './routes/$username/index'
import { Route as DTokenRouteImport } from './routes/d/$token'
import { Route as CartCheckoutRouteImport } from './routes/cart/checkout'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProductsRouteRouteImport } from './routes/admin/products/route'
import { Route as AdminOrdersRouteRouteImport } from './routes/admin/orders/route'
import { Route as AdminEditorRouteRouteImport } from './routes/admin/editor/route'
import { Route as AdminBalanceRouteRouteImport } from './routes/admin/balance/route'
import { Route as AdminAnalyticsRouteRouteImport } from './routes/admin/analytics/route'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminBalanceIndexRouteImport } from './routes/admin/balance/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminEditorProfilesRouteImport } from './routes/admin/editor/profiles'
import { Route as AdminEditorAppearanceRouteImport } from './routes/admin/editor/appearance'
import { Route as UsernameProductsProductIdIndexRouteImport } from './routes/$username/products/$productId/index'
import { Route as UsernameProductsProductIdCheckoutRouteImport } from './routes/$username/products/$productId/checkout'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const UsernameIndexRoute = UsernameIndexRouteImport.update({
  id: '/$username/',
  path: '/$username/',
  getParentRoute: () => rootRouteImport,
} as any)
const DTokenRoute = DTokenRouteImport.update({
  id: '/d/$token',
  path: '/d/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CartCheckoutRoute = CartCheckoutRouteImport.update({
  id: '/cart/checkout',
  path: '/cart/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRouteRoute = AdminProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRouteRoute = AdminOrdersRouteRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEditorRouteRoute = AdminEditorRouteRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBalanceRouteRoute = AdminBalanceRouteRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRouteRoute = AdminAnalyticsRouteRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRouteRoute,
} as any)
const AdminBalanceIndexRoute = AdminBalanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBalanceRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAnalyticsRouteRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AdminProductsRouteRoute,
} as any)
const AdminEditorProfilesRoute = AdminEditorProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminEditorRouteRoute,
} as any)
const AdminEditorAppearanceRoute = AdminEditorAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AdminEditorRouteRoute,
} as any)
const UsernameProductsProductIdIndexRoute =
  UsernameProductsProductIdIndexRouteImport.update({
    id: '/$username/products/$productId/',
    path: '/$username/products/$productId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UsernameProductsProductIdCheckoutRoute =
  UsernameProductsProductIdCheckoutRouteImport.update({
    id: '/$username/products/$productId/checkout',
    path: '/$username/products/$productId/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRouteRouteWithChildren
  '/admin/balance': typeof AdminBalanceRouteRouteWithChildren
  '/admin/editor': typeof AdminEditorRouteRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/d/$token': typeof DTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editor/appearance': typeof AdminEditorAppearanceRoute
  '/admin/editor/profiles': typeof AdminEditorProfilesRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/balance/': typeof AdminBalanceIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/$username/products/$productId/checkout': typeof UsernameProductsProductIdCheckoutRoute
  '/$username/products/$productId/': typeof UsernameProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/editor': typeof AdminEditorRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/d/$token': typeof DTokenRoute
  '/$username': typeof UsernameIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/editor/appearance': typeof AdminEditorAppearanceRoute
  '/admin/editor/profiles': typeof AdminEditorProfilesRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/balance': typeof AdminBalanceIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/$username/products/$productId/checkout': typeof UsernameProductsProductIdCheckoutRoute
  '/$username/products/$productId': typeof UsernameProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/analytics': typeof AdminAnalyticsRouteRouteWithChildren
  '/admin/balance': typeof AdminBalanceRouteRouteWithChildren
  '/admin/editor': typeof AdminEditorRouteRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteRouteWithChildren
  '/admin/products': typeof AdminProductsRouteRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/cart/checkout': typeof CartCheckoutRoute
  '/d/$token': typeof DTokenRoute
  '/$username/': typeof UsernameIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editor/appearance': typeof AdminEditorAppearanceRoute
  '/admin/editor/profiles': typeof AdminEditorProfilesRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/balance/': typeof AdminBalanceIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/$username/products/$productId/checkout': typeof UsernameProductsProductIdCheckoutRoute
  '/$username/products/$productId/': typeof UsernameProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/balance'
    | '/admin/editor'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/auth/callback'
    | '/cart/checkout'
    | '/d/$token'
    | '/$username/'
    | '/admin/'
    | '/admin/editor/appearance'
    | '/admin/editor/profiles'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/analytics/'
    | '/admin/balance/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/$username/products/$productId/checkout'
    | '/$username/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/admin/editor'
    | '/admin/settings'
    | '/auth/callback'
    | '/cart/checkout'
    | '/d/$token'
    | '/$username'
    | '/admin'
    | '/admin/editor/appearance'
    | '/admin/editor/profiles'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/analytics'
    | '/admin/balance'
    | '/admin/orders'
    | '/admin/products'
    | '/$username/products/$productId/checkout'
    | '/$username/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/balance'
    | '/admin/editor'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/auth/callback'
    | '/cart/checkout'
    | '/d/$token'
    | '/$username/'
    | '/admin/'
    | '/admin/editor/appearance'
    | '/admin/editor/profiles'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/admin/analytics/'
    | '/admin/balance/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/$username/products/$productId/checkout'
    | '/$username/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CartCheckoutRoute: typeof CartCheckoutRoute
  DTokenRoute: typeof DTokenRoute
  UsernameIndexRoute: typeof UsernameIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  UsernameProductsProductIdCheckoutRoute: typeof UsernameProductsProductIdCheckoutRoute
  UsernameProductsProductIdIndexRoute: typeof UsernameProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$username/': {
      id: '/$username/'
      path: '/$username'
      fullPath: '/$username/'
      preLoaderRoute: typeof UsernameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$token': {
      id: '/d/$token'
      path: '/d/$token'
      fullPath: '/d/$token'
      preLoaderRoute: typeof DTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/checkout': {
      id: '/cart/checkout'
      path: '/cart/checkout'
      fullPath: '/cart/checkout'
      preLoaderRoute: typeof CartCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/editor': {
      id: '/admin/editor'
      path: '/editor'
      fullPath: '/admin/editor'
      preLoaderRoute: typeof AdminEditorRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/balance': {
      id: '/admin/balance'
      path: '/balance'
      fullPath: '/admin/balance'
      preLoaderRoute: typeof AdminBalanceRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRouteRoute
    }
    '/admin/balance/': {
      id: '/admin/balance/'
      path: '/'
      fullPath: '/admin/balance/'
      preLoaderRoute: typeof AdminBalanceIndexRouteImport
      parentRoute: typeof AdminBalanceRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminAnalyticsRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminProductsRouteRoute
    }
    '/admin/editor/profiles': {
      id: '/admin/editor/profiles'
      path: '/profiles'
      fullPath: '/admin/editor/profiles'
      preLoaderRoute: typeof AdminEditorProfilesRouteImport
      parentRoute: typeof AdminEditorRouteRoute
    }
    '/admin/editor/appearance': {
      id: '/admin/editor/appearance'
      path: '/appearance'
      fullPath: '/admin/editor/appearance'
      preLoaderRoute: typeof AdminEditorAppearanceRouteImport
      parentRoute: typeof AdminEditorRouteRoute
    }
    '/$username/products/$productId/': {
      id: '/$username/products/$productId/'
      path: '/$username/products/$productId'
      fullPath: '/$username/products/$productId/'
      preLoaderRoute: typeof UsernameProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/products/$productId/checkout': {
      id: '/$username/products/$productId/checkout'
      path: '/$username/products/$productId/checkout'
      fullPath: '/$username/products/$productId/checkout'
      preLoaderRoute: typeof UsernameProductsProductIdCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAnalyticsRouteRouteChildren {
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
}

const AdminAnalyticsRouteRouteChildren: AdminAnalyticsRouteRouteChildren = {
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
}

const AdminAnalyticsRouteRouteWithChildren =
  AdminAnalyticsRouteRoute._addFileChildren(AdminAnalyticsRouteRouteChildren)

interface AdminBalanceRouteRouteChildren {
  AdminBalanceIndexRoute: typeof AdminBalanceIndexRoute
}

const AdminBalanceRouteRouteChildren: AdminBalanceRouteRouteChildren = {
  AdminBalanceIndexRoute: AdminBalanceIndexRoute,
}

const AdminBalanceRouteRouteWithChildren =
  AdminBalanceRouteRoute._addFileChildren(AdminBalanceRouteRouteChildren)

interface AdminEditorRouteRouteChildren {
  AdminEditorAppearanceRoute: typeof AdminEditorAppearanceRoute
  AdminEditorProfilesRoute: typeof AdminEditorProfilesRoute
}

const AdminEditorRouteRouteChildren: AdminEditorRouteRouteChildren = {
  AdminEditorAppearanceRoute: AdminEditorAppearanceRoute,
  AdminEditorProfilesRoute: AdminEditorProfilesRoute,
}

const AdminEditorRouteRouteWithChildren =
  AdminEditorRouteRoute._addFileChildren(AdminEditorRouteRouteChildren)

interface AdminOrdersRouteRouteChildren {
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteRouteChildren: AdminOrdersRouteRouteChildren = {
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteRouteWithChildren =
  AdminOrdersRouteRoute._addFileChildren(AdminOrdersRouteRouteChildren)

interface AdminProductsRouteRouteChildren {
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteRouteChildren: AdminProductsRouteRouteChildren = {
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteRouteWithChildren =
  AdminProductsRouteRoute._addFileChildren(AdminProductsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAnalyticsRouteRoute: typeof AdminAnalyticsRouteRouteWithChildren
  AdminBalanceRouteRoute: typeof AdminBalanceRouteRouteWithChildren
  AdminEditorRouteRoute: typeof AdminEditorRouteRouteWithChildren
  AdminOrdersRouteRoute: typeof AdminOrdersRouteRouteWithChildren
  AdminProductsRouteRoute: typeof AdminProductsRouteRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRouteRoute: AdminAnalyticsRouteRouteWithChildren,
  AdminBalanceRouteRoute: AdminBalanceRouteRouteWithChildren,
  AdminEditorRouteRoute: AdminEditorRouteRouteWithChildren,
  AdminOrdersRouteRoute: AdminOrdersRouteRouteWithChildren,
  AdminProductsRouteRoute: AdminProductsRouteRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CartCheckoutRoute: CartCheckoutRoute,
  DTokenRoute: DTokenRoute,
  UsernameIndexRoute: UsernameIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  UsernameProductsProductIdCheckoutRoute:
    UsernameProductsProductIdCheckoutRoute,
  UsernameProductsProductIdIndexRoute: UsernameProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
